language: scala
sudo: false
dist: trusty
scala:
  - 2.11.12
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update
  - sbt ++$TRAVIS_SCALA_VERSION assembly
